### ISSUE TITLE
Compiling warning

### ISSUE THREAD

**Issue by estebanCaballero70200** [Amitpatil215/whatsapp_share#1]
I get this message when run and debug my project in flutter 

Note: C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\whatsapp_share-1.0.9\android\src\main\java\com\example\whatsapp_share\FlutterSharePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by Amitpatil215** [comment]
Hi, @estebanCaballero70200  Thanks for your valuable feedback! 
Will take a look at root cause of this warning and try to fix it.

**Comment by Amitpatil215** [comment]
Please upgrade `whatsapp_share` package to `2.0.2` and let me know if this issue persist.
```yml
dependencies:
  whatsapp_share: ^2.0.2
```
