### ISSUE TITLE
"Can't send empty message" Error

### ISSUE THREAD

**Issue by AnshaMansoor** [Amitpatil215/whatsapp_share#16]
I am trying to share a pdf file from getExternalStorageDirectory() to WhatsApp. 

await WhatsappShare.shareFile(
     phone: '911234567890',
     filePath: [_image.path],
);

I have double-checked that the path is correct and file exists. Also checked through File('${dir}/invoice.pdf').existsSync() which returns true. 
But I always get an error that "Can't send empty message"
The same code was working a few days back and then it stopped.
Please help me in this situation

**Comment by Amitpatil215** [comment]
Can you please share the Android version of the test device?

**Comment by AnshaMansoor** [comment]
Yes, Android version is 11

**Comment by Amitpatil215** [comment]
Okay Thanks, will check and let you know

**Comment by AnshaMansoor** [comment]
Thank you so much

**Comment by venky9885** [comment]
For many android 11 versions file is not sharing ,please solve it ASAP

**Comment by AnshaMansoor** [comment]
Hello, is there any update on this?

**Comment by Amitpatil215** [comment]
Hello @venky9885, @AnshaMansoor 
Please upgrade `whatsapp_share` package to `2.0.2` and let me know if it fixes the issue. 
```yml
dependencies:
  whatsapp_share: ^2.0.2
```

**Comment by AnshaMansoor** [comment]
It's working now. But I cannot send files to a number that isn't saved on my phone. Is there a way to do that?

**Comment by Amitpatil215** [comment]
Thanks @AnshaMansoor , for the quick try, I really appreciate it.
As of now there isn't a way to share files to unsaved WhatsApp contacts. Tracking issue at #13

**Comment by AnshaMansoor** [comment]
Okay, Thank you so much for fixing this problem.
