### ISSUE TITLE
Send Message for Specific Contact

### ISSUE THREAD

**Issue by kholyphoenix1** [Amitpatil215/whatsapp_share#2]
Hello, I am not able to send a message to a specific contact even informing the telephone number.
In the WhatsApp window it shows me to select a contact instead of sending the message directly to a contact.
Do I need to do anything else?

Example: +55 82 98888-7777 (Brazil)
Flutter: 5582988887777

**Comment by Amitpatil215** [comment]
HI @kholyphoenix1 , can you please share minimal reproducible code snippet as well as a platform on which you are in (android or ios)?

**Comment by Amitpatil215** [comment]
also there are some limitations to this package
- WhatsApp number must saved in device
- contact must have active WhatsApp
in both of these cases it redirected to contact picker screen in the WhatsApp
