### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by armandojimenez** [Amitpatil215/whatsapp_share#3]
Any plans to update to null-safety? planing to use this package

**Comment by Amitpatil215** [comment]
Sure will upgrade to null safe version, Thanks!

**Comment by armandojimenez** [comment]
Thanks!!!!

**Comment by armandojimenez** [comment]
Hey! do you have any timeframe for this??

**Comment by armandojimenez** [comment]
Hey! Any timeframe for the upgrade?

**Comment by fareesh** [comment]
https://github.com/Amitpatil215/whatsapp_share/pull/5

**Comment by armandojimenez** [comment]
Any plan to support this? still showing as not supported

**Comment by charleshoong97** [comment]
Hi may I know is there any plan for this? still waiting for null safety version

**Comment by anushkapubudu** [comment]
Hello any update?

**Comment by thEpisode** [comment]
I think this package is dead

**Comment by Amitpatil215** [comment]
Please upgrade `whatsapp_share` package to `2.0.2` 
```yml
dependencies:
  whatsapp_share: ^2.0.2
```
