### ISSUE TITLE
Possible to make the phone number optional?

### ISSUE THREAD

**Issue by AdiLaxman** [Amitpatil215/whatsapp_share#4]
Thank you for this wonderful plugin.
I have a suggestion though... Is it possible to make the phone number optional? So that the user can select the preferred contacts from the contact list in WhatsApp and then hit send? The below code from the pub.dev page of the plugin:

```
Future<void> shareFile() async {
    await WhatsappShare.shareFile(
      text: 'Whatsapp share text',
      **phone: '911234567890',**
      filePath: [_image1.path, _image2.path],
    );
  }
```

**Comment by Amitpatil215** [comment]
Hey, @AdiLaxman Thanks for the feedback, will definitely consider your suggestion.

Here is the workaround, if you don't want to bypass WhatsApp contact picker, Just send non empty string to the ```phone```. 

```Dart
Future<void> share() async {
    await WhatsappShare.share(
      text: 'Example share text',
      linkUrl: 'https://flutter.dev/',
      phone: '-',
    );
  }
```

**Comment by AdiLaxman** [comment]
Oh.. Let me try this out. Thank you for the prompt response.!!
